// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Lbct-j-KYqHRFlN9R3fOYzXG6Fg9o2E',
    appId: '1:788986962796:web:75df6fcfb3f0e829d30949',
    messagingSenderId: '788986962796',
    projectId: 'sleep-cycle-buddy',
    authDomain: 'sleep-cycle-buddy.firebaseapp.com',
    storageBucket: 'sleep-cycle-buddy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAuWNZJTp1q9E26a50cs1W7-rb2SAR6o',
    appId: '1:788986962796:android:905bec34ba0e3be3d30949',
    messagingSenderId: '788986962796',
    projectId: 'sleep-cycle-buddy',
    storageBucket: 'sleep-cycle-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj1WHy8W931M9I0GhSosu8yzGg33O6fDU',
    appId: '1:788986962796:ios:f1b93c5427d149f2d30949',
    messagingSenderId: '788986962796',
    projectId: 'sleep-cycle-buddy',
    storageBucket: 'sleep-cycle-buddy.firebasestorage.app',
    iosBundleId: 'com.example.sleepCycleBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj1WHy8W931M9I0GhSosu8yzGg33O6fDU',
    appId: '1:788986962796:ios:f1b93c5427d149f2d30949',
    messagingSenderId: '788986962796',
    projectId: 'sleep-cycle-buddy',
    storageBucket: 'sleep-cycle-buddy.firebasestorage.app',
    iosBundleId: 'com.example.sleepCycleBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Lbct-j-KYqHRFlN9R3fOYzXG6Fg9o2E',
    appId: '1:788986962796:web:49ae8fdd73448127d30949',
    messagingSenderId: '788986962796',
    projectId: 'sleep-cycle-buddy',
    authDomain: 'sleep-cycle-buddy.firebaseapp.com',
    storageBucket: 'sleep-cycle-buddy.firebasestorage.app',
  );
}
